const mongoose = require('mongoose');

const studentAdmissionSchema = new mongoose.Schema({
    status: {
        type: String,
        enum: [
            'DRAFT',
            'SUBMITTED',
            'UNDER_REVIEW',
            'APPROVED',
            'REJECTED',
            'CANCELLED',
            'RENEWAL_PENDING',
            'RENEWED',
        ],
        default: 'DRAFT',
    },
    source: {
        type: String,
        enum: ['MANAGER', 'STUDENT'],
        default: 'MANAGER',
    },

    // Snapshot fields captured at the time of admission.
    student_name: { type: String, required: true, trim: true },
    student_email: { type: String, default: null, lowercase: true, trim: true },
    student_phone: { type: String, required: true, trim: true },
    student_address: { type: String, default: null, trim: true },
    student_dob: { type: Date, default: null },
    student_gender: { type: String, enum: ['MALE', 'FEMALE', 'OTHER'], default: null },

    parent_name: { type: String, required: true, trim: true },
    parent_phone: { type: String, required: true, trim: true },
    parent_email: { type: String, default: null, lowercase: true, trim: true },
    parent_relationship: { type: String, default: 'PARENT', trim: true },

    admission_from: { type: Date, default: null },
    admission_to: { type: Date, default: null },

    // Generated by the system on approval (Student Registration Number).
    reg_no: { type: String, unique: true, sparse: true, trim: true },

    // Links to created users (after approval / onboarding).
    student_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Student', default: null },
    parent_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Parent', default: null },

    created_by_manager_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Manager', default: null },

    submitted_at: { type: Date, default: null },
    reviewed_by: { type: mongoose.Schema.Types.ObjectId, ref: 'Admin', default: null },
    reviewed_at: { type: Date, default: null },
    decision_remarks: { type: String, default: null, trim: true },

    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
}, { timestamps: true });

studentAdmissionSchema.index({ status: 1, createdAt: -1 });
studentAdmissionSchema.index({ student_phone: 1, createdAt: -1 });

module.exports = mongoose.model('StudentAdmission', studentAdmissionSchema);

